### PR TITLE
Fixes the basename .. bug

### LINKED ISSUE #162: basename trims `..` on ext `.*`
I've got a fix, it's slightly slower.  But I'm adding the Rust benchmark system back in so we can fiddle with it.

## TEST

```rust
assert_eq!("..", basename("..", ".*"));
```

## OUTPUT

```
failures:

---- basename::dots stdout ----
	thread 'basename::dots' panicked at 'assertion failed: `(left == right)`
  left: `".."`,
 right: `"."`', src/basename.rs:56:3
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    basename::dots
```

### PR DESCRIPTION
**Pull request by glebm**
Fixes #162 

This incorporates all the Rust tests added by @danielpclark's in #163 and adds a few more. There does not seem to be any noticable performance impact.

### CODE REVIEW

**Comment by glebm** [comment]
Found a few other bugs, will add herer

**Comment by glebm** [comment]
@danielpclark I've updated the PR with some more tests and fixes.

File: src/basename.rs [hunk 1]
```diff
@@ -20,15 +20,88 @@ pub fn basename<'a>(path: &'a str, ext: &str) -> &'a str {
...
-  } else if bytes[left..right].ends_with(ext_bytes) {
-    right -= ext_bytes.len();
+  } else if slice.ends_with(ext_bytes) {
+    return slice.len() - ext_bytes.len();
   }
-  &path[left..right]
+  slice.len()
+}
+
+// TODO: Un-ignore once the functionality has been implemented.
```
Comment (danielpclark) [inline src/basename.rs]: Just so you know Ruby's `File.basename` method explicitly only uses `.*` for splat and nothing else.  So any other implementation would just be for our benefit in Rust and not a Ruby compatible version.

Comment (glebm) [reply src/basename.rs]: That's not the case, I've tested all the examples in the tests case in `irb` in MRI 2.5.0.

See also the Ruby implementation:
https://github.com/ruby/ruby/blob/5a53cbe314203ce63630030110c51e7650d0fc0a/file.c#L4222

But it does seem to be undocumented.

Comment (danielpclark) [reply src/basename.rs]: You can search through Ruby's test suite and the only thing they tests against is `.*` https://github.com/ruby/ruby/blob/3527c05a8f4e189772cdac17f166bd9626c24661/spec/ruby/core/file/basename_spec.rb I'm not sure where I got this information from that long ago but it's rooted in Ruby's practice if not their rule.

Comment (glebm) [reply src/basename.rs]: That's true, but code may still rely on this undocumented behaviour.
I've figured out an easy way to match Ruby exactly here, will send in a moment.

Comment (glebm) [reply src/basename.rs]: I've updated the PR and it should now match even that undocumented Ruby behaviour.
